-- MySQL Script generated by MySQL Workbench
-- sáb 19 nov 2016 13:57:57 AMT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pessoa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pessoa` (
  `id_pessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `CPF` VARCHAR(14) NOT NULL,
  `telefone` VARCHAR(13) NULL,
  PRIMARY KEY (`id_pessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_cliente_pessoa1_idx` (`pessoa_id_pessoa` ASC),
  CONSTRAINT `fk_cliente_pessoa1`
    FOREIGN KEY (`pessoa_id_pessoa`)
    REFERENCES `mydb`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `RECEITA` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Fornecedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `id_Forn` INT NOT NULL AUTO_INCREMENT,
  `fornecedor` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `CNPJ` VARCHAR(11) NULL,
  `endereco` VARCHAR(100) NULL,
  PRIMARY KEY (`id_Forn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categoria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `id_categoria` INT NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estoque` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estoque` (
  `id_estoque` INT NOT NULL AUTO_INCREMENT,
  `est_idproduto` INT NOT NULL,
  `est_id_categoria` INT NOT NULL,
  `QTD_estoque` INT NULL,
  `precoUni` DOUBLE(10,2) NULL,
  `peso` DOUBLE(10,2) NULL,
  `data_venc` DATE NULL,
  `dataRegistro` VARCHAR(45) NULL,
  `est_id_Forn` INT NOT NULL,
  PRIMARY KEY (`id_estoque`),
  INDEX `fk_estoque_produto1_idx` (`est_idproduto` ASC),
  INDEX `fk_estoque_Forncedor1_idx` (`est_id_Forn` ASC),
  INDEX `fk_estoque_categoria1_idx` (`est_id_categoria` ASC),
  CONSTRAINT `fk_estoque_produto1`
    FOREIGN KEY (`est_idproduto`)
    REFERENCES `mydb`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estoque_Forncedor1`
    FOREIGN KEY (`est_id_Forn`)
    REFERENCES `mydb`.`Fornecedor` (`id_Forn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estoque_categoria1`
    FOREIGN KEY (`est_id_categoria`)
    REFERENCES `mydb`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`funcionario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `funcao` VARCHAR(45) NULL,
  `pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_funcionario`),
  INDEX `fk_funcionario_pessoa1_idx` (`pessoa_id_pessoa` ASC),
  CONSTRAINT `fk_funcionario_pessoa1`
    FOREIGN KEY (`pessoa_id_pessoa`)
    REFERENCES `mydb`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carrinho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`carrinho` ;

CREATE TABLE IF NOT EXISTS `mydb`.`carrinho` (
  `id_carrinho` INT NOT NULL AUTO_INCREMENT,
  `carr_id_estoque` INT NOT NULL,
  `qtd_pedido` INT NULL,
  `sub_total` DOUBLE(10,2) NULL,
  PRIMARY KEY (`id_carrinho`),
  INDEX `fk_pedido_estoque1_idx` (`carr_id_estoque` ASC),
  CONSTRAINT `fk_pedido_estoque1`
    FOREIGN KEY (`carr_id_estoque`)
    REFERENCES `mydb`.`estoque` (`id_estoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`venda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`venda` (
  `idvenda` INT NOT NULL,
  `vend_idcliente` INT NOT NULL,
  `vend_idfuncionario` INT NOT NULL,
  `vend_id_carrinho` INT NOT NULL,
  `total` DOUBLE(10,2) NULL,
  `data_vend` DATE NULL,
  PRIMARY KEY (`idvenda`),
  INDEX `fk_venda_cliente_idx` (`vend_idcliente` ASC),
  INDEX `fk_venda_funcionario1_idx` (`vend_idfuncionario` ASC),
  INDEX `fk_venda_carrinho1_idx` (`vend_id_carrinho` ASC),
  CONSTRAINT `fk_venda_cliente`
    FOREIGN KEY (`vend_idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_funcionario1`
    FOREIGN KEY (`vend_idfuncionario`)
    REFERENCES `mydb`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_carrinho1`
    FOREIGN KEY (`vend_id_carrinho`)
    REFERENCES `mydb`.`carrinho` (`id_carrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`medico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`medico` (
  `id_medico` INT NOT NULL AUTO_INCREMENT,
  `med_id_pessoa` INT NOT NULL,
  `CRM` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id_medico`),
  INDEX `fk_medico_pessoa1_idx` (`med_id_pessoa` ASC),
  CONSTRAINT `fk_medico_pessoa1`
    FOREIGN KEY (`med_id_pessoa`)
    REFERENCES `mydb`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`receita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`receita` ;

CREATE TABLE IF NOT EXISTS `mydb`.`receita` (
  `id_receita` INT NOT NULL AUTO_INCREMENT,
  `rec_id_produto` INT NOT NULL,
  `rec_id_funcionario` INT NOT NULL,
  `medico_id_medico` INT NOT NULL,
  PRIMARY KEY (`id_receita`),
  INDEX `fk_receita_produto1_idx` (`rec_id_produto` ASC),
  INDEX `fk_receita_funcionario1_idx` (`rec_id_funcionario` ASC),
  INDEX `fk_receita_medico1_idx` (`medico_id_medico` ASC),
  CONSTRAINT `fk_receita_produto1`
    FOREIGN KEY (`rec_id_produto`)
    REFERENCES `mydb`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receita_funcionario1`
    FOREIGN KEY (`rec_id_funcionario`)
    REFERENCES `mydb`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receita_medico1`
    FOREIGN KEY (`medico_id_medico`)
    REFERENCES `mydb`.`medico` (`id_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
